### ISSUE TITLE
Merging in relevant changes from @coringao's parallel fork

### ISSUE THREAD

**Issue by akien-mga** [lutris/osmose#12]
Hi guys,

You might be interested in the discussion I had with @coringao and the Debian maintainer who sponsored his osmose package for Debian: https://lists.debian.org/debian-devel-games/2016/08/msg00019.html

Basically, @coringao missed our fork and created a new one based off osmose 0.9.96, from which he released a version 1.0 which is now packaged in Debian: https://github.com/coringao/osmose-emulator
The repository sadly lacks any history, which @coringao attributed to being unfamiliar to the git workflow.

With the Debian maintainer, we discussed a posteriori the issue caused by having two parallel forks, and came to an understanding that it would be best to try to merge the two forks together. @caringao's fork apparently also moved to Qt5, so we'd have to check if parts of his implementation can improve our own, and he also dropped unzip/minizip and replaced it by quazip.

I have yet to hear from @coringao whether he would agree (and want to participate) with cherry-picking his changes in the lutris fork, but we can already start assessing the differences between the two repos to see how to improve our own.

Ideally, I hope that @coringao would want to co-maintain our osmose fork so that there is only one new upstream that downstream distributors and potential contributors could refer to. Once the repos are merged together and a new release is made, we should reach out to the various distro maintainers to notify them about the new version (many are still on 0.9.96 or earlier).

Thoughts?

**Comment by strycore** [comment]
There is no need for 2 forks for the same project. I would be in favor of merging @coringao's code into our codebase so we wouldn't lose our commit history (and we can start doing it before hearing back from him). 
You can start diffing and cherrypicking changes and commit them back to our project using the author/commiter feature of git.

**Comment by LocutusOfBorg** [comment]
you can start with patches to apply on top of the .96 version
https://sources.debian.net/src/osmose-emulator/0.9.96-dfsg-1/debian/patches/typo.patch/
https://sources.debian.net/src/osmose-emulator/0.9.96-dfsg-1/debian/patches/osmose-0-9-96-qt.patch/
https://sources.debian.net/src/osmose-emulator/0.9.96-dfsg-1/debian/patches/memory-mapper.patch/
https://sources.debian.net/src/osmose-emulator/0.9.96-dfsg-1/debian/patches/joystick.patch/

and then look at the attached file (sigh having to add .txt to make it uploadable)
[debdiff.txt](https://github.com/lutris/osmose/files/445391/debdiff.txt)

**Comment by akien-mga** [comment]
Thanks @LocutusOfBorg.
- typo.patch: I crafted a git commit for it setting authorship for @coringao, I'll make a pull request (_edit:_ done, #13)
- joystick.patch: not needed (similar fix applied already)
- the other two patches are unbundling minizip by stripping unzip features, which is overkill and not necessary as we already allow building against the system minizip (b5e4697).

Now onwards to checking the developments done for Carlos' 1.0. Our renaming of the `osmose` folder to `emulator` will complicate the work, but it should stay relatively easy :)

**Comment by akien-mga** [comment]
The debdiff show mostly copyright change and indentation/newline cleanup... @coringao was eager to put his credits in the forked code... There are a couple functional changes though, that I'll try to assess.

**Comment by strycore** [comment]
> Now onwards to checking the developments done for Carlos' 1.0. Our renaming of the osmose folder to emulator will complicate the work, but it should stay relatively easy :)

Creating a branch dedicated to merging the projects together will make the job easier, we could rename the folder back to osmose then revert the renaming when we're done with the merge.

**Comment by akien-mga** [comment]
> Creating a branch dedicated to merging the projects together will make the job easier, we could rename the folder back to osmose then revert the renaming when we're done with the merge.

It's fine actually, since there's no commit history to cater for anyway, it's just a matter of copying the files in the proper folder and checking the `git diff` :)

**Comment by akien-mga** [comment]
I'm looking at the diffs, and there's honestly not much to cherry-pick... at least not much that warrants putting one's name in the header of all .cpp and .h files IMHO. It's mostly a default run of `codespell` and a couple changes like dropping zip support. PR incoming with the relevant changes.

**Comment by strycore** [comment]
There's a CREDITS file for contributors, there's no need to modify every single file.

**Comment by akien-mga** [comment]
Noting down here the non-codespell code changes that we should assess (excluding the zip removal changes, since, as mentioned above, I don't think they are good changes):
- `delete` -> `delete[]` https://github.com/coringao/osmose-emulator/blob/master/osmose/OsmoseCore.cpp#L287 (_edit:_ done: b9b010b)
- `osmose2.ini` -> `osmose-emulator.ini` https://github.com/coringao/osmose-emulator/blob/master/OsmoseConfigurationFile.cpp#L75 (second occurence in same file)
- Qt5-relevant diff + new about dialog on `OsmoseGUI.cpp` and `OsmoseGUI.h`: [OsmoseGUI.diff.txt](https://github.com/lutris/osmose/files/445501/OsmoseGUI.diff.txt)
- `Osmose.pro` diff: [Osmose.pro.diff.txt](https://github.com/lutris/osmose/files/445505/Osmose.pro.diff.txt) (no relevant change)
- New .qrc file for new icon: https://github.com/coringao/osmose-emulator/blob/master/OsmoseResources.qrc
- New icon: https://github.com/coringao/osmose-emulator/blob/master/osmose-emulator.xpm

Looks like this:
![spectacle e29222](https://cloud.githubusercontent.com/assets/4701338/18099928/16d2971c-6ee9-11e6-8501-564135def14e.png)

I'll make a PR for the codespell commit and maybe for the `delete` -> `delete[]` change, then we'd have to review the Qt5-related differences.
About renaming the config file, it's actually a more global issue IMO since we should put it in `~/.config/osmose/osmose.ini`.

Well, that was a lot of virtual ink and confusion for some very small changes in the end... :(

**Comment by akien-mga** [comment]
@LocutusOfBorg How did you generate your debdiff? I'm a bit confused by some of the changes that are not part of https://github.com/coringao/osmose-emulator. Are those automerged Debian patches too?

**Comment by akien-mga** [comment]
> - Qt5-relevant diff + new about dialog on `OsmoseGUI.cpp` and `OsmoseGUI.h`: [OsmoseGUI.diff.txt](https://github.com/lutris/osmose/files/445501/OsmoseGUI.diff.txt)

Had a closer look at the diff. Basically it comprises:
- Adding an About window with credits + license info. I'm not against adding it if deemed useful.
- Removing the "Original size (256x192)" option, replacing it by "Original size (512x384)", and then downgrading all "Size x2", "Size x3", "Size x4" and "Size x5"... Which makes now "Size x2 (768x576)" which is bogus as it's actually x1.5 (or x3 the true original size). This change is bogus and should not be cherry-picked -- "Original size" means original console size and should not be changed, as retro players will want to have it. I guess the motive was that the default size appears too small on current monitors with FullHD resolution, but that's hardly a reason to lie about the emulation.
- Couple errors reformulated:

``` diff
-       error = error + "\nCreating default configuration in user's directory.\nPlease configure path or you will save everything in your home directory !";
-       QMessageBox::critical(this, "No configuration file found", error.c_str());
+       error = error + "\nCreating default configuration in user's directory.";
+       QMessageBox::critical(this, "Configuration file not found", error.c_str());
```

``` diff
-       QMessageBox::critical(this, "Oops, we get an error", msg);
+       QMessageBox::critical(this, "Oops, we have an error in the emulator", msg);
```
- A dropped comment: https://github.com/lutris/osmose/blob/master/OsmoseGUI.cpp#L961-L971  
  I don't see a reason for dropping it even if it mentions an EOL distro, the important is the information it conveys.

So apart from the error reformulations and maybe adding an about dialog, not much to cherry-pick IMO.

**Comment by LocutusOfBorg** [comment]
> @LocutusOfBorg How did you generate your debdiff? I'm a bit confused by some of the changes that >are not part of https://github.com/coringao/osmose-emulator. Are those automerged Debian patches >too?

I can answer better if you provide some examples.
Anyway, the 1.0 version is not patched in Debian and the tarball is available here
http://http.debian.net/debian/pool/main/o/osmose-emulator/osmose-emulator_1.0.orig.tar.gz

I used that one

**Comment by akien-mga** [comment]
@LocutusOfBorg Oh I see where my confusion comes from. Your diff is against our version 0.9.96 (i.e. the same base as @coringao's fork), and not the master HEAD / 0.9.97, hence the differences which I did not see when diffing our master HEAD with @coringao's :)

**Comment by akien-mga** [comment]
I think we can consider this issue fixed. @strycore Should we tag 0.9.98?

**Comment by strycore** [comment]
I'm fine with this!

**Comment by strycore** [comment]
Tag pushed!

**Comment by LocutusOfBorg** [comment]
please ping when you release :)

**Comment by LocutusOfBorg** [comment]
@coringao  can you please apply this as update on top of your version?
you can call it
`1.0.is.0.98-1`

**Comment by ghost** [comment]
I will change the version. But we need to fix the part of compilation architecture "armel".

**Comment by akien-mga** [comment]
@strycore You haven't bump the release in the source. :)

**Comment by akien-mga** [comment]
```
$ rg 0\.9\.97
emulator/Version.h
37:#define __OSMOSE_VERSION__ "Osmose 0.9.97"

README
9:       Version 0.9.97 - public release, written by Bruno Vedder.
```

**Comment by LocutusOfBorg** [comment]
also, the xpm file disappeared...

**Comment by LocutusOfBorg** [comment]
@coringao I'm attaching the Debian directory, don't waste too much time about arm\* failures, we might look at them after.
Look more deeply about copyrights, e.g. zip\* aren't listed in debian/copyright file.
[debian.zip](https://github.com/lutris/osmose/files/556992/debian.zip)

**Comment by akien-mga** [comment]
I did not import the xpm file as it did not bring (IMO) much value to our png icon (and looked much different, so confusing).

**Comment by akien-mga** [comment]
You can strip the `unzip` folder from the Debian archive, it's not needed if building against system minizip.

**Comment by ghost** [comment]
@LocutusOfBorg I have to put the copyright of 'unzip'. But then the package becomes "contrib" or "non-free"?

**Comment by ghost** [comment]
The version is wrong, please correct.

**Comment by LocutusOfBorg** [comment]
```
+   Copyright (C) 1998-2003 Gilles Vollant
+   Copyright (C) 1998-2003 Gilles Vollant
+   Copyright (C) 1998-2003 Gilles Vollant
+   Copyright (C) 1998-2003 Gilles Vollant
+  Copyright (c) 1990-2000 Info-ZIP.  All rights reserved.
```

the license should be "zlib/libpng", and still dfsg

**Comment by akien-mga** [comment]
Or as I mentioned, just repack without unzip and you don't have to document a license of something you don't bundle :)

It's pretty common for upstream projects to bundle their libraries, and for downstream distributors to unbundle them.

**Comment by ghost** [comment]
@LocutusOfBorg okay, so need to fix the version

**Comment by akien-mga** [comment]
I'll make a PR to fix the version.

**Comment by ghost** [comment]
@akien-mga Perfect ;)

**Comment by akien-mga** [comment]
@coringao Alright, version fixed and git tag redone (that's bad to rewrite history this way, but it was fresh enough to do IMO).

**Comment by ghost** [comment]
I will do packing. Thanks!

**Comment by akien-mga** [comment]
Also don't hesitate to open issues if there are things that could be further improved both packaging-wise and regarding the program itself. Having specific issues to work on helps stimulate contributions :D

**Comment by ghost** [comment]
@akien-mga What was even missing is the fixed icon in the window, could add '.qrc'. :)

**Comment by akien-mga** [comment]
@coringao It seems to work for me without .qrc file, the icon is attached to the binary.
![spectacle b21886](https://cloud.githubusercontent.com/assets/4701338/19786887/6f1551d2-9ca0-11e6-9e00-e9c167d3c144.png)
Haven't checked if it works on Windows though.

**Comment by ghost** [comment]
![osmose-icon](https://cloud.githubusercontent.com/assets/289377/19787440/7ed4414c-9c81-11e6-8191-0e42ec8a2b72.jpg)
Here is not shown the icon, run the binary out of the compiled directory.

**Comment by akien-mga** [comment]
Hm, it works for me even out of the compilation dir, but it might be some caching Plasma does. Would you make a PR with the needed .qrc file?

**Comment by ghost** [comment]
Yes, I notice when finished. :)
