### ISSUE TITLE
Port to Qt5

### ISSUE THREAD

**Issue by akien-mga** [lutris/osmose#3]
We are now in the Qt5 era, so if it's not too difficult, having a Qt5 port would be pretty cool. From what I could see in other projects going from Qt4 to Qt5 is relatively easy; I might have a look at it.

**Comment by strycore** [comment]
Honestly, if there was a way to remove the Qt dependency altogether and port everything to SDL2/OpenGL that'd be even better. I realize that this would require a major rewrite of the whole project so, for the time being, updating to Qt5 is the right thing to do :ok_hand:

**Comment by akien-mga** [comment]
For the emulation part it would likely be feasible with SDL2/OpenGL, but for the GUI part it would likely be way more difficult to code a basic toolkit from scratch IMO, so it's probably safer to stay with Qt 5. It's also arguably way more stable that GTK+3 so we won't have to fix regressions at every point release :)
