### ISSUE TITLE
New stable maintenance release

### ISSUE THREAD

**Issue by akien-mga** [lutris/osmose#4]
The last release goes back to June 2011, since there are a few improvements in this repo, it would be nice to make a new release, e.g. 0.9.97 or something.

**Comment by strycore** [comment]
Agreed. I've mailed the original author of Osmose to let him know of our branch. It would be nice if the new version was also used upstream.

**Comment by akien-mga** [comment]
Did you get any answer from the original author? Once my proposed changes are integrated I can do some testing and see if we're release ready.

**Comment by strycore** [comment]
I wrote to the author and never got an answer, I also searched around the web to see if I could find what he's up to now but couldn't find anything either. Guess we can manage the project however we want now, as long as we keep credits for the original author.

**Comment by akien-mga** [comment]
I didn't have much time to do play testing, but from my short tests the current master branch seems to behave fine. I'd propose to just tag 0.9.97 now officially, and hopefully if some third-party notice it we'll get some more testers and contributions. WDYT?

**Comment by strycore** [comment]
Yep, seems about right. I'll tag this as a new release.

**Comment by akien-mga** [comment]
Fixed. :)
