### ISSUE TITLE
"make clean" tries to remove "core" folder

### ISSUE THREAD

**Issue by akien-mga** [lutris/osmose#6]
Looks like "core" was a poor name choice when renaming the "osmose" dir, as QMake has hardcoded instructions to try to remove it with `make clean` (assuming that `core` or `*.core` are results of a core dump).

See: https://forum.qt.io/topic/12782/make-clean-tries-to-remove-directory-core/5

Not sure it's worth renaming the core folder again though. Let's see if QMake from Qt5 works better :)

**Comment by strycore** [comment]
I've renamed the directory to emulator, that should prevent any issue from qmake.
